version: '3'

services:
  postgresdb:
    container_name: postgres
    build: ./requirements/DB/
    volumes:
      - DB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transcenDB
    expose:
      - "5432"
    networks:
      - transcendance
    restart: unless-stopped

  webapp:
    container_name: webapp
    build: ./requirements/webapp/
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    networks:
      - transcendance
    restart: unless-stopped
    
volumes:
  DB:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: ~/Postgres_volume
      
networks:
  transcendance:
    driver: bridge