version: '3'

services:
  postgresdb:
    container_name: postgres
    build: ./requirements/DB/
    volumes:
      - DB:/var/lib/postgresql/data
    env_file:
      - ./requirements/DB/.env
    expose:
      - "5432"
    networks:
      - transcendance
    restart: unless-stopped

  webapp:
    container_name: webapp
    build: ./requirements/ft_transcendance/
    env_file:
      - ./requirements/ft_transcendance/.env
    depends_on:
      - postgresdb
    ports:
      - "8000:8000"
    networks:
      - transcendance
    restart: unless-stopped
    
volumes:
  DB:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /root/Postgres_volume
      
networks:
  transcendance:
    driver: bridge