version: '3.8'

services:
  postgresdb:
    container_name: postgres
    build: ./requirements/DB/
    volumes:
      - DB:/var/lib/postgresql/data
    env_file:
      - ./requirements/DB/.env
    expose:
      - "5432"
    networks:
      - transcendance
    restart: unless-stopped

  webapp:
    container_name: webapp
    build: ./requirements/ft_transcendance/
    env_file:
      - ./requirements/ft_transcendance/.env
    depends_on:
      - postgresdb
    expose:
      - "8000"
    networks:
      - transcendance
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    # build: ./requirements/nginx/
    image: nginx:latest
    volumes:
      - ./requirements/NGINX/nginx.conf:/etc/nginx/nginx.conf
      - ./requirements/NGINX/html/index.html:/usr/share/nginx/html/index.html
      - ./requirements/NGINX/html/bundle.js:/usr/share/nginx/html/bundle.js
    depends_on:
      - webapp
    ports:
      - "80:80"
    networks:
      - transcendance
    restart: unless-stopped
  
volumes:
  DB:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /Users/alexandreselnet/Coding/Postgres_volume
      
networks:
  transcendance:
    driver: bridge