version: '3.8'
services:
  postgresdb:
    container_name: postgres
    build: ./requirements/DB/
    volumes:
      - DB:/var/lib/postgresql/data
    env_file:
      - ./requirements/DB/.env
    expose:
      - "5432"
    networks:
      - transcendance
    restart: unless-stopped

  webapp:
    container_name: webapp
    build: ./requirements/ft_transcendance/
    volumes:
      - STATIC:/home/ft_transcendance/static/
      - MEDIA:/home/ft_transcendance/media/
    env_file:
      - ./requirements/ft_transcendance/.env
    depends_on:
      - postgresdb
    expose:
      - "8000"
    networks:
      - transcendance
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    build: ./requirements/NGINX
    volumes:
      - STATIC:/var/www/static
      - MEDIA:/var/www/media/
    depends_on:
      - webapp
    ports:
      - "4443:4443"
    networks:
      - transcendance
    restart: unless-stopped

  redis:
    container_name: redis
    build: ./requirements/REDIS
    depends_on: 
      - postgresdb
    expose:
      - "6380"
    networks:
      - transcendance
    restart: unless-stopped
  
volumes:
  DB:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /tmp/volumes/Postgres_volume

  STATIC:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /tmp/volumes/Static_volume
    
  MEDIA:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: /tmp/volumes/Media_volume
      
networks:
  transcendance:
    driver: bridge
