version: '3'

services:
  postgresdb:
    container_name: postgres
    build: ./DB/
    volumes:
      - DB:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: transcenDB
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: unless-stopped
    
volumes:
  DB:
    driver: local
    driver_opts:
      type: volumes
      o: bind
      device: ~/Postgres_volume