# Generated by Django 5.0.4 on 2024-05-06 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_transcendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='test',
        ),
    ]
